defaultBagSlots: 9
frameMaterial: "BLACK_STAINED_GLASS_PANE"
warnings:
  lockedSlot: "&e[!]&7 Bu slota eşya koymak için daha iyi bir çantaya ihtiyacın var."
  lockedSlotClick: "&e[!]&7 Bu slotu açmak için çanta kullanmalısın."
items:
  Küçük Çanta:
    material: CHEST
    slot: 18

  Büyük Çanta:
    material: CHEST
    slot: 36